### ISSUE TITLE
How to delete a branch

### ISSUE THREAD

**Issue by hegoku** [nickperkinslondon/angular-bootstrap-nav-tree#106] opened 2016-08-05 08:05 UTC
I can't find a delete function in source code... Is there any solutions? Thanks!

**Comment by guicoma** [comment] 2016-09-07 10:11
To have a function in the directive (just like add_branch) would be great.

For the meantime I worked around this by travelling the tree and replacing the data:

```
function deleteTreeItems(tree, items) {
  for (var i = 0; i < tree.length; i++) {
    for (var j = 0; j < items.length; j++) {
      if (tree[i].id == items[j].id) {
        tree.splice(i,1);
        i = 0;
      } else {
        if (tree[i].children.length > 0) {
          tree[i].children = deleteTreeItems(tree[i].children, items);
        }
      }
    }
  }
  return tree;
}
```

**Comment by hegoku** [comment] 2016-09-07 12:27
Yep, Great!

**Comment by rbw0** [comment] 2016-11-20 23:09
Hello,

There's already a PR for this, so I'm not gonna create another.
Anyway, I did it like this.

```
tree.remove_branch = function(branch) {
  if (branch != null) {
    var parent = get_parent(branch);
    // Make sure we have a parent
    if(parent != null) {
      parent.children.splice(parent.children.indexOf(branch), 1);
    }
  }
};
```

**Comment by daerogami** [comment] 2019-08-29 03:37
Duplicate of #36

**Closed by daerogami** 2019-08-29 03:37 UTC
