### ISSUE TITLE
can we add sort functionality to the tree view ?

### ISSUE THREAD

**Issue by vsonone** [nickperkinslondon/angular-bootstrap-nav-tree#54] opened 2014-10-30 10:38 UTC
How difficult will it be to add sort and filter feature to this tree ?

**Comment by benoror** [comment] 2015-02-11 16:14
Filtering issue duplicated at: https://github.com/nickperkinslondon/angular-bootstrap-nav-tree/issues/47

**Comment by benoror** [comment] 2015-02-18 18:19
I would also like to filter elements from the nav-tree using a search input, any idea?

**Comment by justjoheinz** [comment] 2015-07-14 15:29
+1

**Comment by trondhuso** [comment] 2016-01-21 12:23
+1 also

**Comment by daerogami** [comment] 2019-08-29 07:21
As previously mentioned, this is a duplicate of #47

**Closed by daerogami** 2019-08-29 07:21 UTC
