### ISSUE TITLE
catch expand/collapse vs select

### ISSUE THREAD

**Issue by trondhuso** [nickperkinslondon/angular-bootstrap-nav-tree#94] opened 2016-01-21 12:26 UTC
First of:
Nick: Thanks for creating such a great directive!

When I am using this directive I call some APIs based on user actions. Just that I don't want to call these APIs when someone is just expanding or collapsing the node. Is there a way to distinguish between selecting and expanding/collapsing?

**Comment by guicoma** [comment] 2016-08-05 09:47
There are also people with the same interest in another issue #66

**Comment by daerogami** [comment] 2019-08-29 07:51
Duplicate of #66

**Closed by daerogami** 2019-08-29 07:51 UTC
Labels: duplicate
