### ISSUE TITLE
add tree#remove_branch(branch) function

### ISSUE THREAD

**Issue by brighthas** [nickperkinslondon/angular-bootstrap-nav-tree#43] opened 2014-05-27 11:40 UTC
add tree#remove_branch(branch) function

look this

https://github.com/brighthas/angular-bootstrap-nav-tree/commit/dd1816b52dda0e5905e67a2c3f418d7992432e52

**Comment by daerogami** [comment] 2019-08-29 06:49
Duplicate of #36

**Closed by daerogami** 2019-08-29 06:49 UTC
